### ISSUE TITLE
favicon.png does not get installed with 'pip install pyarbtools' on Windows 10

### ISSUE THREAD

**Issue by emcware** [morgan-at-keysight/pyarbtools#60]
After installing pyarbtools using pip on a Windows 10 system with Pycharm and Python 3.10, I received the following error message 

Traceback (most recent call last):
  File "C:\Users\45207\PycharmProjects\example tkinter\examples\pyarbtools examples\pyarbtools gui example.py", line 4, in <module>
    pyarbtools.gui.main()
  File "C:\Users\45207\PycharmProjects\example tkinter\venv3_9\lib\site-packages\pyarbtools\gui.py", line 1283, in main
    root.iconbitmap(iconPath)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 2080, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "C:\Users\45207\PycharmProjects\example tkinter\venv3_9\lib\site-packages\pyarbtools\favicon.png" not defined.

The python file consists of two lines of code:
import pyarbtools

pyarbtools.gui.main()

I tried uninstalling and reinstalling pyarbtools but saw the same error.
The same pip installation worked sucessfully on Mac OS using python 3.10.

 I have an MXG N5182B and the vsg examples worked fine (very nice package - I am excited to learn/use this package!)
I assume I can just copy the favicon.png to my venv as a workaround.

**Comment by morgan-at-keysight** [comment]
I've removed the icon from the GUI. It was causing way too many issues. This issue is solved in version 2025.06.1.
